apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: election-app
build:
  artifacts:
    - image: gcr.io/election-app/web
      context: src/web
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    sha256: {}
  googleCloudBuild: {}
deploy:
  kubectl:
    manifests:
      - kubernetes/web.yaml
      - metrics/podmonitor.yaml
